@startuml
set separator none
title Sellingpower

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("OrderManagementServiceApplication.OrderManagementServiceApplication_boundary", "OrderManagementServiceApplication", $tags="") {
  Component(OrderManagementServiceApplication.OrderManagementServiceApplication.Order, "Order", $techn="Module", $descr="", $tags="", $link="")
  Component(OrderManagementServiceApplication.OrderManagementServiceApplication.Corporateaction, "Corporateaction", $techn="Module", $descr="", $tags="", $link="")
  Component(OrderManagementServiceApplication.OrderManagementServiceApplication.Sellingpower, "Sellingpower", $techn="Module", $descr="", $tags="", $link="")
}

Rel(OrderManagementServiceApplication.OrderManagementServiceApplication.Sellingpower, OrderManagementServiceApplication.OrderManagementServiceApplication.Corporateaction, "listens to", $techn="", $tags="", $link="")
Rel(OrderManagementServiceApplication.OrderManagementServiceApplication.Sellingpower, OrderManagementServiceApplication.OrderManagementServiceApplication.Order, "listens to", $techn="", $tags="", $link="")
Rel(OrderManagementServiceApplication.OrderManagementServiceApplication.Order, OrderManagementServiceApplication.OrderManagementServiceApplication.Sellingpower, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml