@startuml
set separator none
title Corporateaction

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("OrderManagementServiceApplication.OrderManagementServiceApplication_boundary", "OrderManagementServiceApplication", $tags="") {
  Component(OrderManagementServiceApplication.OrderManagementServiceApplication.Corporateaction, "Corporateaction", $techn="Module", $descr="", $tags="", $link="")
  Component(OrderManagementServiceApplication.OrderManagementServiceApplication.Marketdata, "Marketdata", $techn="Module", $descr="", $tags="", $link="")
  Component(OrderManagementServiceApplication.OrderManagementServiceApplication.Buyingpower, "Buyingpower", $techn="Module", $descr="", $tags="", $link="")
  Component(OrderManagementServiceApplication.OrderManagementServiceApplication.Sellingpower, "Sellingpower", $techn="Module", $descr="", $tags="", $link="")
  Component(OrderManagementServiceApplication.OrderManagementServiceApplication.Account, "Account", $techn="Module", $descr="", $tags="", $link="")
}

Rel(OrderManagementServiceApplication.OrderManagementServiceApplication.Corporateaction, OrderManagementServiceApplication.OrderManagementServiceApplication.Marketdata, "depends on", $techn="", $tags="", $link="")
Rel(OrderManagementServiceApplication.OrderManagementServiceApplication.Corporateaction, OrderManagementServiceApplication.OrderManagementServiceApplication.Account, "depends on", $techn="", $tags="", $link="")
Rel(OrderManagementServiceApplication.OrderManagementServiceApplication.Corporateaction, OrderManagementServiceApplication.OrderManagementServiceApplication.Buyingpower, "depends on", $techn="", $tags="", $link="")
Rel(OrderManagementServiceApplication.OrderManagementServiceApplication.Corporateaction, OrderManagementServiceApplication.OrderManagementServiceApplication.Sellingpower, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml